name: Test All Services and Packages

on:
  pull_request:
    branches: [ main ]
  push:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [services/*, packages/*]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test ${{ matrix.folder }}
        uses: ./.github/actions/test-service-or-package
        with:
          target_path: ${{ matrix.folder }}
